version: "3"

services:

  webserver:
    build:
      context: ./bin/rocky:8/php:74
    container_name: php74-webserver
    image: rocky8/php74:1
    restart: 'always'
    expose:
      - 80
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./data/www:/var/www
      - ./config/httpd:/etc/httpd/conf.d
      - ./data/logs/webserver:/etc/httpd/logs
    privileged: true

  database:
    image: mariadb:10.6
    container_name: php74-db
    restart: 'always'
    networks:
      - back-tier
    expose:
      - 3306
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/database:/var/lib/mysql
      - ./data/logs/database:/var/log/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_name
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_password

  proxy:
    image: nginx
    container_name: php74-proxy
    restart: 'always'
    depends_on:
      - webserver
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:3306:3306"
    networks:
      - front-tier
      - back-tier
    volumes:
       - ./config/proxy/http:/etc/nginx/conf.d
       - ./config/proxy/stream:/etc/nginx/stream.d
       - ./config/proxy/default.conf:/etc/nginx/nginx.conf
    # command:
      # - "apt-get update"
      # - "apt-get install inetutils-ping -y"

networks:
  front-tier:
  back-tier: